### ISSUE TITLE
It can not worked well ,and the log is blow,please help me ,thank you!

### ISSUE THREAD

**Issue by liuxgchi** [joniks/Android-MuPDF#16]
FATAL EXCEPTION: main
    Process: com.sunnymum.xing, PID: 17390
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sunnymum.client-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libmupdf.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:988)
            at com.artifex.mupdfdemo.MuPDFCore.<clinit>(MuPDFCore.java:16)
            at com.artifex.mupdfdemo.MuPDFActivity.openFile(MuPDFActivity.java:212)
            at com.artifex.mupdfdemo.MuPDFActivity.onCreate(MuPDFActivity.java:308)

**Comment by Luatnd98** [comment]
Can you show me how to fix it? Thank you!
